<?php
/**
 * GroupsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * GroupsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GroupsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createAccountExtensionContactGroup
     *
     * Add a new contact group to an account extension..
     *
     */
    public function testCreateAccountExtensionContactGroup()
    {
    }

    /**
     * Test case for deleteAccountExtensionContactGroup
     *
     * Delete a contact group from the address book..
     *
     */
    public function testDeleteAccountExtensionContactGroup()
    {
    }

    /**
     * Test case for getAccountExtensionContactGroup
     *
     * Retrieve the information of a contact group..
     *
     */
    public function testGetAccountExtensionContactGroup()
    {
    }

    /**
     * Test case for listAccountExtensionContactGroups
     *
     * Show a list of contact groups belonging to an extension..
     *
     */
    public function testListAccountExtensionContactGroups()
    {
    }

    /**
     * Test case for replaceAccountExtensionContactGroup
     *
     * Update the information of a contact group..
     *
     */
    public function testReplaceAccountExtensionContactGroup()
    {
    }
}
