<?php
/**
 * ListenersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ListenersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ListenersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createAccountListener
     *
     * Add a listener object to your account that can be used to subscribe an event..
     *
     */
    public function testCreateAccountListener()
    {
    }

    /**
     * Test case for deleteAccountListener
     *
     * Delete an individual event listener..
     *
     */
    public function testDeleteAccountListener()
    {
    }

    /**
     * Test case for getAccountListener
     *
     * Show details of an individual listener..
     *
     */
    public function testGetAccountListener()
    {
    }

    /**
     * Test case for listAccountListeners
     *
     * Get a list of listeners for an account..
     *
     */
    public function testListAccountListeners()
    {
    }

    /**
     * Test case for replaceAccountListener
     *
     * Update the settings of an individual event listener..
     *
     */
    public function testReplaceAccountListener()
    {
    }
}
