<?php
/**
 * OauthclientsredirecturisApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * OauthclientsredirecturisApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OauthclientsredirecturisApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createAccountOauthClientsRedirectUri
     *
     * Create an OAuth Client Redirect URI record..
     *
     */
    public function testCreateAccountOauthClientsRedirectUri()
    {
    }

    /**
     * Test case for deleteAccountOauthClientsRedirectUri
     *
     * Delete an OAuth Client Redirect URI record..
     *
     */
    public function testDeleteAccountOauthClientsRedirectUri()
    {
    }

    /**
     * Test case for getAccountOauthClientsRedirectUri
     *
     * Get details of an OAuth Client Redirect URI record..
     *
     */
    public function testGetAccountOauthClientsRedirectUri()
    {
    }

    /**
     * Test case for listAccountOauthClientsRedirectUris
     *
     * Get a list of OAuth Client Redirect URIs for an account..
     *
     */
    public function testListAccountOauthClientsRedirectUris()
    {
    }
}
