<?php
/**
 * SubaccountpricingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SubaccountpricingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SubaccountpricingApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createAccountSubaccountPricing
     *
     * Add a pricing plan to a subaccount..
     *
     */
    public function testCreateAccountSubaccountPricing()
    {
    }

    /**
     * Test case for deleteAccountSubaccountPricing
     *
     * Delete a pricing plan from a subaccount..
     *
     */
    public function testDeleteAccountSubaccountPricing()
    {
    }

    /**
     * Test case for getAccountSubaccountPricing
     *
     * Get the details of a pricing plan for a subaccount..
     *
     */
    public function testGetAccountSubaccountPricing()
    {
    }

    /**
     * Test case for listAccountSubaccountPricing
     *
     * Get a list of pricing plans for a subaccount..
     *
     */
    public function testListAccountSubaccountPricing()
    {
    }
}
