<?php
/**
 * CreateExtensionParamsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Phone.com API
 *
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateExtensionParamsTest Class Doc Comment
 *
 * @category    Class */
// * @description CreateExtensionParams
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateExtensionParamsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CreateExtensionParams"
     */
    public function testCreateExtensionParams()
    {

    }

    /**
     * Test attribute "voicemail"
     */
    public function testPropertyVoicemail()
    {

    }

    /**
     * Test attribute "call_notifications"
     */
    public function testPropertyCallNotifications()
    {

    }

    /**
     * Test attribute "caller_id"
     */
    public function testPropertyCallerId()
    {

    }

    /**
     * Test attribute "usage_type"
     */
    public function testPropertyUsageType()
    {

    }

    /**
     * Test attribute "allows_call_waiting"
     */
    public function testPropertyAllowsCallWaiting()
    {

    }

    /**
     * Test attribute "extension"
     */
    public function testPropertyExtension()
    {

    }

    /**
     * Test attribute "include_in_directory"
     */
    public function testPropertyIncludeInDirectory()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "full_name"
     */
    public function testPropertyFullName()
    {

    }

    /**
     * Test attribute "timezone"
     */
    public function testPropertyTimezone()
    {

    }

    /**
     * Test attribute "name_greeting"
     */
    public function testPropertyNameGreeting()
    {

    }

    /**
     * Test attribute "local_area_code"
     */
    public function testPropertyLocalAreaCode()
    {

    }

    /**
     * Test attribute "enable_outbound_calls"
     */
    public function testPropertyEnableOutboundCalls()
    {

    }

    /**
     * Test attribute "enable_call_waiting"
     */
    public function testPropertyEnableCallWaiting()
    {

    }

}
